import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";



export default function Home() {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="main-container">
        <div className="page01">
        
          <div className="navbar">

            <div className="logo">
              <Image
              className={styles.logo}
              src="/navbarlogo.png"
              alt="Next.js logo"
              width={240}
              height={80}             
            />
            </div>

            <div className="nav-links littleRed">
              <a href="">Sobre nós</a>
              <a href="">Cursos</a>
              <a href="">Blog do sabor</a>
              <a href="">Fale conosco</a>
            </div>

            <div className="social-medias">
              <a href="https://www.instagram.com" target="_blank" rel="noopener noreferrer">
                <i className="fab fa-instagram fa-2x"></i>
              </a>
              <a href="https://www.facebook.com" target="_blank" rel="noopener noreferrer">
                <i className="fab fa-facebook fa-2x"></i>
              </a>
              <a href="https://twitter.com" target="_blank" rel="noopener noreferrer">
                <i className="fab fa-twitter fa-2x"></i>
              </a>
              <a href="https://wa.me" target="_blank" rel="noopener noreferrer">
                <i className="fab fa-whatsapp fa-2x "></i> 
              </a>
            </div>

          </div>
        
        <main className={styles.main}>
          <div className="main-01">
            <div>
              <h3 className="littleGray">Seja bem-vindo ao</h3>
            </div>
            <div>
              <h1 className="bigGray">INSTITUTO DO</h1> 
            </div>
            <div>
              <h1 className="bigRed">SABOR</h1>
            </div>

            <div>
              <p className="littleGray">Descubra nossa formação <b className="strong-highlight">completa em</b></p>
            </div>
            
            <div>
              <p className="littleGray"> <b className="strong-highlight">gastronomia</b> e transforme sua paixão pela</p>
            </div>  
            <div>
              <p className="littleGray">culinária em uma <b className="strong-highlight">carreira de sucesso!</b></p>
            </div>
            <button className="redbutton">QUERO SABER MAIS</button>

    
          </div>

          
          
          </main>
        </div>
      </div>

      <div className="secondPageContainer">
        <div className="page02">
          <div className="main-02">
            <div className="page02-text">
              <div>
                <h1 className="bigH1Red">TRANSFORMAMOS SUA PAIXÃO PELA</h1>
              </div>
              <div>
                <h1 className="bigH1Yellow">CULINÁRIA EM CARREIRA DE SUCESSO</h1>
              </div>
              <div>
                <p className="littleGrayPG2">Ensinando Técnicas e segredos para atuar em restaurantes,</p>
              </div>
              <div>
                <p p className="littleGrayPG2">bares ou abrir seu próprio negócio. Nosso objetivo é prepará-lo</p>
              </div>
              <div>
                <p p className="littleGrayPG2">para os desafios do mundo gastronômico. <b className="trong-highlight">Junte-se a nós e</b></p>
              </div>
              <div>
                <p p className="littleGrayPG2"><b className="trong-highlight">inicie sua jornada com o pé direito!</b></p>
              </div>
              <button className="redbutton buttonPG02">SEJA NOSSO ALUNO</button>
              </div>
          </div>
          
        </div>
      </div>

      <div className="thirdPageContainer">
        <div className="page03">
            <div className="titleThirdPage">
              <h1 className="titleThirdPageGray">CONHEÇA NOSSOS <span className="titleThirdPageRed">COMBOS EXCLUSIVOS</span></h1>
            </div>
        </div>
      </div>
      
      <footer>
        <div className="footerText">
          <p>Instituto do Sabor – Escola de Gastronomia. © Todos os direitos reservados. Desenvolvido por Vertical Marketing</p>
        </div> 
      </footer>

    </>
  );
}
